### ISSUE TITLE
Firefox social Services API addition requires being on https version of page

### ISSUE THREAD

**Issue by jaywink** [sharetodiaspora/sharetodiaspora.github.io#14]
Clicking the button to enable service does nothing at least on Firefox developer edition 40 if not on HTTPS version of the page.

How can this be dealt with on gh-pages?

**Comment by fdavidcl** [comment]
It looks like GitHub cannot be forced to use HTTPS by default, but there's [this](https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it) guide on how to redirect users to HTTPS. I'll give it a try.

**Comment by fdavidcl** [comment]
It seems to work fine now on Firefox Developer Edition. The HTTPS redirection is currently only enabled for the *about* page. Should it affect the main page as well?

**Comment by jaywink** [comment]
Great, thanks @fdavidcl for your awesome work with this! :cookie: 

I'm not sure it needs to be on the normal pages, I guess HTTPS is always good, so I don't see any harm. But I'll close this issue from here as it's solved.
