### ISSUE TITLE
Bookmarklet version that uses og:image metadata if available

### ISSUE THREAD

**Issue by tukkek** [sharetodiaspora/sharetodiaspora.github.io#19]
(Sorry for using a GH issue for this but inter-pod D* messaging didn't seem to be working.)

Hello saw your site share-to-diaspora and hacked you boorkmarklet a bit. I'm sending you the source in case you're interested!

This bookmarklet (which I call "Share image on diaspora*") is useful in two use-cases:

1. Share a webpage which has og:image metadata. In this case the image will be inlined and present the source URL as well.

2. Share an image (JPG for example) that you've got open in your browser. In this case the image will be inlined as above, using the syntax `![Image](url)`

Tested on Firefox and probably requires the user to not check the "use markdown syntax for links", which is a bummer.

Maybe you can salvage something useful from this since the current bookmarklet, that shares without having an image is pretty poor in many use cases.

`javascript:(function(){image=document.querySelector('meta[property="og:image"]')&&document.querySelector('meta[property="og:image"]').getAttribute('content');f='http://sharetodiaspora.github.io/?title='+encodeURIComponent((image?'**'+document.title+'** ':'')+'!['+(image?document.title:'Image')+']('+(image||window.location.href)+')')+'&v=1&';a=function(){if(!window.open(f+'noui=1&jump=doclose&url='+encodeURIComponent(window.location.href),'diasporav1','location=yes,links=no,scrollbars=yes,toolbar=no,width=620,height=550'))location.href=f+'jump=yes'};if(/Firefox/.test(navigator.userAgent)){setTimeout(a,0)}else{a()}})()`

**Comment by fdavidcl** [comment]
Hi! 

That bookmarklet is pretty great, I'll add it to the bookmarklet section in the *about* page.
I might try to tweak it later so that it can be used with the markdown option.

Thank you very much!
