### ISSUE TITLE
Am I supposed to be able to use a custom POD ?

### ISSUE THREAD

**Issue by strk** [sharetodiaspora/sharetodiaspora.github.io#21]
When I enter my pod url I get it on the right with a red background, but clicking on it does nothing, is it supposed to be using my custom url for sharing ?

**Comment by schiessle** [comment]
Yes, this seems to be broken. 😢  Does anybody still care? The project seems to be quite inactive since a few months.

**Comment by fdavidcl** [comment]
Hi, thanks the comments. I'm afraid I haven't had the time to maintain the project lately. Clicking on custom links should be working now.

**Comment by schiessle** [comment]
Great, works again! Thanks a lot! :)
