### ISSUE TITLE
share button missing due to podupi error?

### ISSUE THREAD

**Issue by lupa18** [sharetodiaspora/sharetodiaspora.github.io#22]
I'm not sure but is seems to be something broken... we can't use this anymore.. screenshot:

Error is: 
GET https://podupti.me/api.php [HTTP/2.0 500 Internal Server Error 296ms]

**Comment by fdavidcl** [comment]
Hi, thanks for the comment. You're right that Poduptime is not returning the pod list anymore. The site is using a static list now so it should work as expected.
