### ISSUE TITLE
License information for JavaScript

### ISSUE THREAD

**Issue by MasterOfTheTiger** [sharetodiaspora/sharetodiaspora.github.io#27]
Add [license information](https://www.gnu.org/software/librejs/) about all the Javascript used by Share to Diaspora* so that it is compatible with LibreJS.

I would be willing to work on it, but I need to know if this is currently maintained, and what method should be used to implement this.

**Comment by fdavidcl** [comment]
Hi,

This project is not actively maintained since there is an official fork: [diaspora/sharetodiaspora](https://github.com/diaspora/sharetodiaspora). I think any new contributions should be proposed there.

Thanks.

**Comment by MasterOfTheTiger** [comment]
Oh thank you. I should probably use that for sharing to Diaspora* as well.
