### ISSUE TITLE
Please document where the pod list comes from

### ISSUE THREAD

**Issue by grinapo** [sharetodiaspora/sharetodiaspora.github.io#28]
Since I have to figure out why it lists my old pod and not the new, and there are numerous lists available on the net....

**Comment by jaywink** [comment]
Unfortunately this project is pretty much unmaintained. I'm not using Diaspora for years myself. But happy to merge in PR's that improve it, as I have the rights to do so.

Should a maintainer step up, we can also discuss giving collaborator or owner rights.
